# Generated by Django 5.2.8 on 2025-11-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NodeType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("node_id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="nodes.nodetype",
                    ),
                ),
            ],
            options={
                "ordering": ["node_id"],
                "indexes": [
                    models.Index(
                        fields=["node_id"], name="nodes_node_node_id_ef6689_idx"
                    ),
                    models.Index(fields=["type"], name="nodes_node_type_id_798559_idx"),
                ],
            },
        ),
    ]
