# Generated by Django 5.2.8 on 2025-11-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=100)),
                ("default_value", models.CharField(max_length=255)),
                ("sensitive", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("group", models.CharField(blank=True, max_length=100)),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "display_order", "property_name"],
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="metadata.metadataconfig",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="metadataconfig",
            index=models.Index(
                fields=["content_type", "object_id", "property_name"],
                name="metadata_me_content_88def8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metadataconfig",
            unique_together={("content_type", "object_id", "property_name")},
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["content_type", "object_id", "metadata"],
                name="metadata_me_content_170a9b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metadata",
            unique_together={("content_type", "object_id", "metadata")},
        ),
    ]
